name: 🐍 Generate Snake Contribution Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animation SVGs
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Roshu-3158
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg

      # Step 3: Commit the generated SVGs to the repo
      - name: Commit snake animation
        uses: EndBug/add-and-commit@v9
        with:
          message: "🐍 Add snake contribution animation"
          add: "output/*"
